# Investigating the Dentist data

In [1]:
# Imports and Utility Functions
from collectors import Scraper, CsvCollector
from config import URL, MY_POSTCODE, ADMISSION_CATEGORIES
import pandas as pd


import io
import requests

In [2]:
# Set up and Download CSV
ctr = CsvCollector(URL)
cx = ctr.connect()
results = ctr.search_postcode(cx, MY_POSTCODE)
# sheet = ctr.download_csv(ctr.csv_url)
s=requests.get(ctr.csv_url).content
df=pd.read_csv(io.StringIO(s.decode('utf-8')))

In [3]:
# Pandas
# df = ctr.listlist_to_df(sheet)
df.head()

,Organisation Name,NACS Code,Organisation Type,Address1,Address2,Address3,Address4,Address5,PostCode,Telephone Number,...,Value (Accepting new adult patients entitled to free NHS dental care),Banding Classification (Accepting new adult patients entitled to free NHS dental care),Accepting children as new NHS patients,Value (Accepting children as new NHS patients),Banding Classification (Accepting children as new NHS patients),Urgent NHS dental appointments,Value (Urgent NHS dental appointments),Banding Classification (Urgent NHS dental appointments),Induction loop (Induction loop in place),Car parking (Is there car parking at this organisation?)
0,Mr N H Douglas,V02621,DEN,Wathen Road Dental Care,3-4 Wathen Road,NaN,Dorking,NaN,RH4 1JU,Tel: 01306 740044,...,Data not available,question,No data supplied by the dental practice,Data not available,question,No data supplied by the dental practice,Data not available,question,no,yes
1,Old Courthouse Dental Practice,V09849,DEN,277 High Street,NaN,NaN,Dorking,NaN,RH4 1RY,Tel: 01306 885611,...,Data not available,question,No data supplied by the dental practice,Data not available,question,No data supplied by the dental practice,Data not available,question,no,no
2,"mydentist, St Martin’s Walk, Dorking",V09328,DEN,"Unit 4, St Martin's Walk Shopping Centre",Mill Lane,NaN,Dorking,Surrey,RH4 1UT,Tel: 013 0674 0840,...,false,no,NaN,false,no,NaN,false,no,Data not available,yes
3,IDH Limited,V58878,DEN,4 ST. MARTINS WALK,DORKING,NaN,NaN,NaN,RH4 1UT,NaN,...,Data not available,question,No data supplied by the dental practice,Data not available,question,No data supplied by the dental practice,Data not available,question,NaN,NaN
4,Portman Healthcare Limited,V37799,DEN,Longborough Dental Surgery,Reigate Road,DORKING,Surrey,NaN,RH4 1QE,NaN,...,Data not available,question,No data supplied by the dental practice,Data not available,question,No data supplied by the dental practice,Data not available,question,NaN,NaN

In [4]:
print(df.columns[13])

print(df.columns[14])
# df.columns

Accepting NHS patients by referral only
Value  (Accepting NHS patients by referral only)

In [5]:
admission_categories = ADMISSION_CATEGORIES
import pprint
pp = pprint.PrettyPrinter(indent=4)
pp.pprint(admission_categories)
# list(admission_categories.values())

{   'by_referral': 'Value  (Accepting NHS patients by referral only)',
    'new_adult': 'Value  (Accepting new adult NHS patients)',
    'new_adult_entitled': 'Value  (Accepting new adult patients entitled to '
                          'free NHS dental care)',
    'new_children': 'Value  (Accepting children as new NHS patients)',
    'urgent_nhs': 'Value  (Urgent NHS dental appointments)'}

In [6]:
cat = admission_categories
admission_subset = df[[
    'Organisation Name', 
    'PostCode', 
    'Telephone Number', 
]
    + list(cat.values())
]
admission_subset.head()

,Organisation Name,PostCode,Telephone Number,Value (Accepting NHS patients by referral only),Value (Accepting new adult NHS patients),Value (Accepting new adult patients entitled to free NHS dental care),Value (Accepting children as new NHS patients),Value (Urgent NHS dental appointments)
0,Mr N H Douglas,RH4 1JU,Tel: 01306 740044,Data not available,Data not available,Data not available,Data not available,Data not available
1,Old Courthouse Dental Practice,RH4 1RY,Tel: 01306 885611,Data not available,Data not available,Data not available,Data not available,Data not available
2,"mydentist, St Martin’s Walk, Dorking",RH4 1UT,Tel: 013 0674 0840,false,false,false,false,false
3,IDH Limited,RH4 1UT,NaN,Data not available,Data not available,Data not available,Data not available,Data not available
4,Portman Healthcare Limited,RH4 1QE,NaN,Data not available,Data not available,Data not available,Data not available,Data not available

In [12]:
admission_filter = cat['new_children']
filtered = admission_subset[
    df[
        admission_filter
    ] == 'true'
]
filtered

,Organisation Name,PostCode,Telephone Number,Value (Accepting NHS patients by referral only),Value (Accepting new adult NHS patients),Value (Accepting new adult patients entitled to free NHS dental care),Value (Accepting children as new NHS patients),Value (Urgent NHS dental appointments)
26,"mydentist, Ashley Road, Epsom",KT18 5BH,Tel: 013 7272 5128,false,true,true,true,true
29,Epsom Orthodontics,KT17 4PF,Tel: 01372 749040,false,false,false,true,true
32,Mr K Christian,KT17 4DB,Tel: 01372 722685,false,true,true,true,true
37,River Mole Dental,KT11 1HT,Tel: 01932 866252,false,true,true,true,false
39,Mr K H Nasser,SM7 1PB,Tel: 01737 219955,false,true,true,true,true
...,...,...,...,...,...,...,...,...
1327,"CROSBIE, Alan James Rednal",SL6 8AJ,Tel: 01628 623584,false,true,true,true,false
1328,Elias Mr K,N8 0PH,Tel: 020 8888 1002,false,true,true,true,true
1330,Forest Dental Practice,E7 9LW,Tel: 020 8552 1010,false,true,true,true,true
1333,Mr Dineen & Associates,E10 5QE,Tel: 020 8558 6036,false,true,true,true,false
1335,West Green Dental Practice,N15 3PA,Tel: 020 8888 2408,false,true,true,true,true